function quant_tbl_coh = wmh_ud2_initCohQuantTbl (ud2param)

wmh_ud2_initCohQuantTbl_startTime = tic;
fprintf ('%s :\n', mfilename);
fprintf ('%s : Started (%s).\n', mfilename, string(datetime));

n_meas = 194;

varTypes = cell (n_meas,1);

varTypes (1)     = {'cellstr'}; % 1st variable is ID.
varTypes (2:end) = {'single'};  % 2nd to last are measures in 'single'
								% data type.

quant_tbl_coh = table ('Size',          [ud2param.n_subjs n_meas], ...
					   'VariableTypes', varTypes);

quant_tbl_coh.Properties.VariableNames =   {'subjID'
											'wbwmh_vol'
											'pvwmh_vol'
											'dwmh_vol'
											'lfron_vol'
											'rfron_vol'
											'ltemp_vol'
											'rtemp_vol'
											'lpari_vol'
											'rpari_vol'
											'locci_vol'
											'rocci_vol'
											'lcere_vol'
											'rcere_vol'
											'brnstm_vol'
											'unid_lob_vol'
											'raah_vol'
											'laah_vol'
											'rmah_vol'
											'lmah_vol'
											'raaml_vol'
											'laaml_vol'
											'raac_vol'
											'laac_vol'
											'rmall_vol'
											'lmall_vol'
											'rpatmp_vol'
											'lpatmp_vol'
											'rpah_vol'
											'lpah_vol'
											'rpac_vol'
											'lpac_vol'
											'unid_art_vol'
											'wbwmh_noc'
											'wbwmh_noc_p'
											'wbwmh_noc_f'
											'wbwmh_noc_m'
											'wbwmh_noc_c'
											'pvwmh_noc'
											'lfron_noc'
											'rfron_noc'
											'ltemp_noc'
											'rtemp_noc'
											'lpari_noc'
											'rpari_noc'
											'locci_noc'
											'rocci_noc'
											'lcere_noc'
											'rcere_noc'
											'brnstm_noc'
											'unid_lob_noc'
											'pvwmh_noc_p'
											'lfron_noc_p'
											'rfron_noc_p'
											'ltemp_noc_p'
											'rtemp_noc_p'
											'lpari_noc_p'
											'rpari_noc_p'
											'locci_noc_p'
											'rocci_noc_p'
											'lcere_noc_p'
											'rcere_noc_p'
											'brnstm_noc_p'
											'unid_lob_noc_p'
											'pvwmh_noc_f'
											'lfron_noc_f'
											'rfron_noc_f'
											'ltemp_noc_f'
											'rtemp_noc_f'
											'lpari_noc_f'
											'rpari_noc_f'
											'locci_noc_f'
											'rocci_noc_f'
											'lcere_noc_f'
											'rcere_noc_f'
											'brnstm_noc_f'
											'unid_lob_noc_f'
											'pvwmh_noc_m'
											'lfron_noc_m'
											'rfron_noc_m'
											'ltemp_noc_m'
											'rtemp_noc_m'
											'lpari_noc_m'
											'rpari_noc_m'
											'locci_noc_m'
											'rocci_noc_m'
											'lcere_noc_m'
											'rcere_noc_m'
											'brnstm_noc_m'
											'unid_lob_noc_m'
											'pvwmh_noc_c'
											'lfron_noc_c'
											'rfron_noc_c'
											'ltemp_noc_c'
											'rtemp_noc_c'
											'lpari_noc_c'
											'rpari_noc_c'
											'locci_noc_c'
											'rocci_noc_c'
											'lcere_noc_c'
											'rcere_noc_c'
											'brnstm_noc_c'
											'unid_lob_noc_c'
											'raah_noc'
											'laah_noc'
											'rmah_noc'
											'lmah_noc'
											'raaml_noc'
											'laaml_noc'
											'raac_noc'
											'laac_noc'
											'rmall_noc'
											'lmall_noc'
											'rpatmp_noc'
											'lpatmp_noc'
											'rpah_noc'
											'lpah_noc'
											'rpac_noc'
											'lpac_noc'
											'unid_art_noc'
											'raah_noc_p'
											'laah_noc_p'
											'rmah_noc_p'
											'lmah_noc_p'
											'raaml_noc_p'
											'laaml_noc_p'
											'raac_noc_p'
											'laac_noc_p'
											'rmall_noc_p'
											'lmall_noc_p'
											'rpatmp_noc_p'
											'lpatmp_noc_p'
											'rpah_noc_p'
											'lpah_noc_p'
											'rpac_noc_p'
											'lpac_noc_p'
											'unid_art_noc_p'
											'raah_noc_f'
											'laah_noc_f'
											'rmah_noc_f'
											'lmah_noc_f'
											'raaml_noc_f'
											'laaml_noc_f'
											'raac_noc_f'
											'laac_noc_f'
											'rmall_noc_f'
											'lmall_noc_f'
											'rpatmp_noc_f'
											'lpatmp_noc_f'
											'rpah_noc_f'
											'lpah_noc_f'
											'rpac_noc_f'
											'lpac_noc_f'
											'unid_art_noc_f'
											'raah_noc_m'
											'laah_noc_m'
											'rmah_noc_m'
											'lmah_noc_m'
											'raaml_noc_m'
											'laaml_noc_m'
											'raac_noc_m'
											'laac_noc_m'
											'rmall_noc_m'
											'lmall_noc_m'
											'rpatmp_noc_m'
											'lpatmp_noc_m'
											'rpah_noc_m'
											'lpah_noc_m'
											'rpac_noc_m'
											'lpac_noc_m'
											'unid_art_noc_m'
											'raah_noc_c'
											'laah_noc_c'
											'rmah_noc_c'
											'lmah_noc_c'
											'raaml_noc_c'
											'laaml_noc_c'
											'raac_noc_c'
											'laac_noc_c'
											'rmall_noc_c'
											'lmall_noc_c'
											'rpatmp_noc_c'
											'lpatmp_noc_c'
											'rpah_noc_c'
											'lpah_noc_c'
											'rpac_noc_c'
											'lpac_noc_c'
											'unid_art_noc_c'
											'avg_clstr_dist'
											'std_clstr_dist'
											'var_clstr_dist'
											'avg_clstrSiz'
											'std_clstrSiz'
											'var_clstrSiz'};

wmh_ud2_initCohQuantTbl_finishTime = toc (wmh_ud2_initCohQuantTbl_startTime);
fprintf ('%s : Finished (%s; %.4f seconds elapsed).\n', mfilename, string(datetime), wmh_ud2_initCohQuantTbl_finishTime);
fprintf ('%s :\n', mfilename);